Contact data split
lvoytek/wedding-site pull request #15
Opened 2023-02-07 02:16 UTC by lvoytek

Split contact data and RSVP data to better match the database structure and make user data more dynamic

2023-02-12 23:52 UTC, lboje commented on client/src/app/forms/rsvp/rsvp.component.ts
> +	@Output() submit = new EventEmitter<RecursivePartial<primaryData & contactData & rsvpData>>()
Don't be mad - this might be a thing we want to have as a separate type. This is..a little gross.

2023-02-12 23:53 UTC, lboje commented on client/src/app/forms/rsvp/rsvp.component.ts
> +		let rsvpData: RecursivePartial<primaryData & contactData & rsvpData>;
Same here

2023-02-12 23:53 UTC, lboje commented on client/src/app/rsvp/rsvp.component.ts
> +	sendForm(rsvpData: RecursivePartial<primaryData & contactData & rsvpData>){
Third place :(

2023-02-12 23:59 UTC, lboje commented on server/src/guest/guest.controller.ts
> +		| guestData
why is the | before the guestData?

2023-02-13 00:00 UTC, lvoytek commented on server/src/guest/guest.controller.ts
> +		| guestData
huh wierd

2023-02-13 00:03 UTC, lboje commented on server/src/guest/guest.controller.ts
> +		| (rsvpData & contactData & primaryData)
I don't really like this as our type for the Promise. It's almost not useful?

2023-02-13 00:03 UTC, lboje commented on server/src/guest/guest.controller.ts
> +		| (rsvpData & contactData & primaryData)
As in - how do I act on what I'll get back?

2023-02-13 00:04 UTC, lboje commented on server/src/rsvp/rsvp.controller.ts
> +		@Body() rsvp: primaryData & contactData & rsvpData,
Ths _does_ exist on your side :p

2023-02-13 00:05 UTC, lboje requested changes
left a few comments

2023-02-13 00:08 UTC, lboje commented on server/src/guest/guest.controller.ts
> +		| (rsvpData & contactData & primaryData)
Sorry to comment spam - 
Specifically, I don't like the combination of (rsvpData & contactData & primaryData) OR (rsvpData & primaryData)

The former will contain the latter, which feels a bit redundant. If we just get this down to guestData | (the combined type thing), that'll probably be fine

2023-02-13 00:19 UTC, lboje commented on libs/types/person.d.ts
> +type guestData = primaryData & contactData & rsvpData & assignmentData;
```suggestion
type guestData = rsvpSubmissionData & assignmentData;
```

2023-02-13 00:23 UTC, lboje approved these changes

2023-02-13 00:23 UTC, merged